// Shared store for 3-slot pickup authorizations per child
export const pickupAuthorizationsStore: Record<string, any[]> = {
  'STU-001': [
    {
      id: 'AUTH-01',
      slot_number: 1,
      name: 'John Okafor',
      category: 'family_member',
      category_label: 'Family Member',
      relationship: 'Uncle',
      phone: '+234 803 112 4455',
      photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      emergency_notes: 'Primary emergency contact. Has authorization on weekdays.',
      is_verified: true,
      confirmed_by_parent: true,
      confirmed_at: '2026-08-20T10:00:00Z',
      gate_synced: true,
    },
    {
      id: 'AUTH-02',
      slot_number: 2,
      name: 'Babajide Adeleke',
      category: 'escort',
      category_label: 'School Escort',
      relationship: 'Assigned School Bus Escort',
      phone: '+234 803 291 8841',
      photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      emergency_notes: 'Official Gracefield bus route VI-EXP-01 escort.',
      is_verified: true,
      confirmed_by_parent: true,
      confirmed_at: '2026-08-21T09:30:00Z',
      gate_synced: true,
    },
  ],
};
